version: '3.7'

services:
  client:
    build:
      context: client
    image: belvo/quickstart:client
    environment:
      BELVO_ENV: ${BELVO_ENV}
    ports:
    - 8080:8080
    networks:
      - quickstart-net

  server:
    build:
      context: node
    image: belvo/quickstart:node
    environment:
      BELVO_SECRET_ID: ${BELVO_SECRET_ID}
      BELVO_SECRET_PASSWORD: ${BELVO_SECRET_PASSWORD}
      BELVO_ENV: ${BELVO_ENV}
      COMPANY_ICON_URL: ${COMPANY_ICON_URL}
      COMPANY_LOGO_URL: ${COMPANY_LOGO_URL}
      COMPANY_NAME: ${COMPANY_NAME}
      COMPANY_BENEFIT_HEADER: ${COMPANY_BENEFIT_HEADER}
      COMPANY_BENEFIT_CONTENT: ${COMPANY_BENEFIT_CONTENT}
      COMPANY_OPPORTUNITY_LOSS: ${COMPANY_OPPORTUNITY_LOSS}
    ports:
      - 5000:5000
    networks:
      - quickstart-net

networks:
  quickstart-net: {}
